# Generated by Django 6.0.3 on 2026-04-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
