# Generated by Django 6.0.3 on 2026-04-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transactiontype_code_alter_transactiontype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='code',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('withdraw', 'Retiro')], max_length=20, unique=True),
        ),
    ]
